### ISSUE TITLE
Can you please add sleep mode please 

### ISSUE THREAD

**Issue by Skaveny** [nagyrobi/home-assistant-custom-components-linkplay#14]
Please can you build in a sleep timer function in your component, I really need that because I use your component to play relaxing music when I’m going to sleep and I don’t want it to play all night I need a function that stops music after 30/60/120 minutes

**Comment by nagyrobi** [comment]
Do you see any sleep timer options available for your device in the Android app (4stream)?
Some Linkplay devices have this already built-in, I could integrate that in HA. Although there's no documentation available about it, I'll have to dig into it some more.

**Comment by Skaveny** [comment]
I’m running iOS and my speakers maker is Audio Pro and it seems that audio pro app doesn’t have any sleep timer option, the only way I can get sleep timer is inside Spotify app but it only have 60 minutes the longest time I’m after 30/60/90/130/120 option to set timer on, so if you have time please add that function please

**Comment by nagyrobi** [comment]
Well you should first with 4Stream app (I see it's [available](https://apps.apple.com/us/app/4stream/id1446722739) in Ios too), do you have sleep timer option available for your Audio Pro speaker. If not, unfortunately your speaker doesn't support natively sleep function.

What you could do, is to create in Home Assistant, a sleep timer independent from the speaker model:
- create an input boolean, named for example `start_sleep_30`
- create an automation which triggers when the input boolean changes to True, at actions add a delay of `00:30:00`, and add a call the service `media_player.media_stop` for `entity_id: media_player.your_audiopro_linkplay`. You can also add a service `input_boolean.turn_off` for `entity_id: input_boolean.start_sleep_30` so that it resets back after stopping the player.
- create the above for each sleep delay you want.
- in Lovelace the input boolean will look like a switch. All you have to do is turn the switch on and the player will be stopped after the specified delay.

This is fairly simple like this. Setting it up with any Linkplay-specific services would make it more complicated because some automations and modules would be needed anyway to have some Lovelace interface...

**Comment by Skaveny** [comment]
I found a sleep timer function in the app in speaker settings, I’m trying to setup a sleep timer but I can’t get it to work I’m using HA Web GUI, I can more or less nothing about automation and script, I normally search on Google after script/automation and copy and paste and change the script, I have made 2 screenshots of my setup can you see what I have made wrong?
![F6A1AA69-12AF-4F1B-B0FB-3D1AD2F2E690](https://user-images.githubusercontent.com/1252745/93774822-f3a4b700-fc21-11ea-9a50-6125cad7ee5e.jpeg)
![E486A287-2DCB-47F8-9CBD-C81FE25CE94B](https://user-images.githubusercontent.com/1252745/93774829-f56e7a80-fc21-11ea-990c-f972aa615dda.jpeg)

**Comment by nagyrobi** [comment]
This should be fine. You could do tests with shorter delays, and when everything runs fine, just modify it to final desired delay.

**Comment by Skaveny** [comment]
Hello Again can you explain how I make a drop down menu so it contains 30/60/120/240 select time options?

**Comment by nagyrobi** [comment]
Well I guess you could use an `input_select` for that. Search for how to do it on Home Assistant forums, see for example:

https://community.home-assistant.io/t/slider-input-delay-off-switch-help-what-have-i-done-wrong/53496/2
